version: '3.8'

services:
  postgres-cdc:
    image: postgres:15
    container_name: postgres-cdc
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=football_source
    command: ["postgres", "-c", "wal_level=logical"]
    restart: always

  sync-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: sync-worker
    depends_on:
      - postgres-cdc
    environment:
      - FOOTBALL_PG_HOST=postgres-cdc
      - FOOTBALL_PG_PORT=5432
      - FOOTBALL_PG_USER=postgres
      - FOOTBALL_PG_PASS=postgres
      - FOOTBALL_PG_DB=football_source
    restart: always
