version: '3.8'

services:
  postgres-cdc:
    image: postgres:15
    container_name: postgres-cdc
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=football_source
    command: ["postgres", "-c", "wal_level=logical"]
    restart: always
