USE ROLE ACCOUNTADMIN;
USE WAREHOUSE FOOTBALL_WH;
USE DATABASE FOOTBALL_DWH;
USE SCHEMA RAW;

-- 1. BẢNG RAW CHO API-FOOTBALL (P24)
CREATE OR REPLACE TABLE API_FOOTBALL_FIXTURES (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE API_FOOTBALL_TEAMS (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE API_FOOTBALL_PLAYERS (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);

-- 2. BẢNG RAW CHO CÁC NGUỒN KHÁC (P03 - P25)
CREATE OR REPLACE TABLE FOOTBALL_DATA_CO_UK (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE WIKIDATA (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE THESPORTSDB (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE FOOTBALL_DATA_ORG (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE WIKIMEDIA (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE OPEN_METEO (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE PHYSIOROOM (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE UNDERSTAT (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE WIKIPEDIA (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE GOOGLE_NEWS (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE YOUTUBE (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE ODDS_API (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE FOOTBALL_NEWS (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);

-- 3. TẠO STAGE KẾT NỐI VỚI MINIO (CÚ PHÁP MỚI CHO S3-COMPATIBLE)
-- CHÚ Ý QUAN TRỌNG TỪ SNOWFLAKE:
-- 1. URL phải dùng 's3compat://' thay vì 's3://'
-- 2. Endpoint KHÔNG ĐƯỢC chứa số cổng (port 9000 không được hỗ trợ). 
--    Snowflake bắt buộc Endpoint phải là HTTPS (port 443) có chứng chỉ TLS hợp lệ.
-- 3. Bạn không cần tạo Storage Integration cho s3compat.
CREATE OR REPLACE STAGE MINIO_BRONZE_STAGE
  URL = 's3compat://football-lake/bronze/'
  ENDPOINT = '20.41.113.183.nip.io' -- Tên miền này trỏ thẳng về IP của bạn, đã được bọc HTTPS
  CREDENTIALS = (AWS_KEY_ID = 'minioadmin' AWS_SECRET_KEY = 'minioadmin123');

-- Nếu bạn không thể cài Nginx HTTPS cho MinIO, giải pháp duy nhất là:
-- Sửa DAG của Airflow: dùng LocalFilesystemToSnowflakeOperator (tải từ MinIO xuống Airflow Worker, rồi upload lên Snowflake Internal Stage).
