-- ==========================================
-- BƯỚC 1: KHỞI TẠO MÔI TRƯỜNG CƠ BẢN
-- ==========================================
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE FOOTBALL_WH;
CREATE DATABASE IF NOT EXISTS FOOTBALL_DWH;
CREATE SCHEMA IF NOT EXISTS FOOTBALL_DWH.RAW;

USE DATABASE FOOTBALL_DWH;
USE SCHEMA RAW;

-- ==========================================
-- BƯỚC 2: TẠO TÀI KHOẢN AIRFLOW VÀ PHÂN QUYỀN
-- ==========================================
-- Tạo một User mới dành riêng cho Airflow
CREATE USER IF NOT EXISTS AIRFLOW_SVC
  PASSWORD = 'Airflow123'  -- Pass mặc định, sẽ bị vô hiệu hóa vì dùng Key-Pair
  LOGIN_NAME = 'AIRFLOW_SVC'
  DEFAULT_ROLE = SYSADMIN
  DEFAULT_WAREHOUSE = FOOTBALL_WH
  DEFAULT_NAMESPACE = FOOTBALL_DWH.RAW
  COMMENT = 'Service account cho Airflow tự động đẩy data';

-- Gán Key-Pair Authentication cho Airflow User
ALTER USER AIRFLOW_SVC
SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvpIvQcWSXoJIAVMaJ9Tz7hzUBut5hMyvjMg0nPD1jAF3ki7qw+exVsU6eelVlcE2cKQqJ0pS+V0QICHo+7TS/LOGlPLbmL7IvC3togX2rZJSSSa5ZXCJiqqCmpc09ddOu2Ji+tINQ0Y9Ne7fVVp6HVPJVgmwC4fIeIlrB3F8ClNrbdVqI59smEPg7lQpm1mvTjqh5mwwAYEjWPUrcx3uOyVK3CRof3LpezQFfD3PoDGxiKmMYnl8Lx37XYpe3Xq0zszr//Jj49atM6NvndKz9KkCJrrWlNfvh4KgUe7rWJuVM3wYPIarJ3DzNBs3T3jeTmYFy361eridb2z6KRDrOQIDAQAB';

-- Cấp quyền SYSADMIN cho Airflow User
GRANT ROLE SYSADMIN TO USER AIRFLOW_SVC;

-- Cấp các quyền sử dụng Database, Schema và Warehouse cho SYSADMIN
GRANT ALL PRIVILEGES ON DATABASE FOOTBALL_DWH TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON SCHEMA FOOTBALL_DWH.RAW TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE FOOTBALL_WH TO ROLE SYSADMIN;

-- ==========================================
-- BƯỚC 3: TẠO BẢNG RAW DỮ LIỆU
-- ==========================================
-- Bảng RAW cho API-FOOTBALL (P24)
CREATE OR REPLACE TABLE API_FOOTBALL_FIXTURES (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE API_FOOTBALL_TEAMS (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE API_FOOTBALL_PLAYERS (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);

-- Bảng RAW cho các nguồn khác (P03 - P25)
CREATE OR REPLACE TABLE FOOTBALL_DATA_CO_UK (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE WIKIDATA (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE THESPORTSDB (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE FOOTBALL_DATA_ORG (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE WIKIMEDIA (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE OPEN_METEO (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE PHYSIOROOM (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE UNDERSTAT (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE WIKIPEDIA (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE GOOGLE_NEWS (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE YOUTUBE (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE ODDS_API (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE FOOTBALL_NEWS (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);

-- ==========================================
-- BƯỚC 4: TẠO STAGE NỘI BỘ VÀ CẤP QUYỀN BẢNG
-- ==========================================
-- Tạo stage trung chuyển để Airflow Python đẩy file vào
CREATE OR REPLACE STAGE MINIO_RAW_STAGE
  DIRECTORY = (ENABLE = TRUE);

-- Cấp quyền cho SYSADMIN truy cập các Tables và Stages hiện tại & tương lai
GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA FOOTBALL_DWH.RAW TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FOOTBALL_DWH.RAW TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FOOTBALL_DWH.RAW TO ROLE SYSADMIN;
