USE ROLE ACCOUNTADMIN;
USE WAREHOUSE FOOTBALL_WH;
USE DATABASE FOOTBALL_DWH;
USE SCHEMA RAW;

-- 1. BẢNG RAW CHO API-FOOTBALL (P24)
CREATE OR REPLACE TABLE API_FOOTBALL_FIXTURES (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE API_FOOTBALL_TEAMS (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE API_FOOTBALL_PLAYERS (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);

-- 2. BẢNG RAW CHO CÁC NGUỒN KHÁC (P03 - P25)
CREATE OR REPLACE TABLE FOOTBALL_DATA_CO_UK (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE WIKIDATA (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE THESPORTSDB (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE FOOTBALL_DATA_ORG (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE WIKIMEDIA (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE OPEN_METEO (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE PHYSIOROOM (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE UNDERSTAT (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE WIKIPEDIA (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE GOOGLE_NEWS (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE YOUTUBE (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE ODDS_API (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE FOOTBALL_NEWS (RAW_DATA VARIANT, INGEST_TIMESTAMP TIMESTAMP_NTZ);

-- 3. TẠO STAGE KẾT NỐI VỚI MINIO (CÚ PHÁP MỚI CHO S3-COMPATIBLE)
CREATE OR REPLACE STAGE MINIO_RAW_STAGE
  URL = 's3compat://football-lake/raw/'
  ENDPOINT = '20.41.113.183.nip.io'
  CREDENTIALS = (AWS_KEY_ID = 'minioadmin' AWS_SECRET_KEY = 'minioadmin123');
